server:
  port: 8096
  servlet:
    context-path: /lsso-resource-server
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8095/auth/realms/lsso
          jwk-set-uri: http://localhost:8095/auth/realms/lsso/protocol/openid-connect/certs
          jws-algorithm: RS256
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringLssoResource
    username: root
    password: truong00
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect